### ISSUE TITLE
MLB games being picked every 3 days - 

### ISSUE THREAD

**Issue by sr735** [kjorg50/ripe-sports#1]
Is this intended functionality? @etaba 
![image](https://user-images.githubusercontent.com/5414504/33750863-a8c1e988-db8b-11e7-91ed-a96ea466bedf.png)
![image](https://user-images.githubusercontent.com/5414504/33750865-ad732aaa-db8b-11e7-9773-4803cfec749b.png)

**Comment by etaba** [comment]
Yeah, depending on the sport and number of games in a day, espn fits a fixed number of days per pag for each league. For mlb, if you search 1/1/2017 you'll get the games for 1/1-1/3. If you then scrape the date 1/2 you'll get games from 1/2-1/4, and hence repeat games from 1/2 and 1/3. Instead search every third day. For nba its different, and nfl too, thats why the number of days per page is an input to the scraper method
